{{- if .Values.useRBAC }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "controller.fullname" . }}
rules:
- apiGroups: ["", "extensions", "apps", "rbac.authorization.k8s.io"] # "" indicates the core API group
  resources:
    - configmaps
    - deployments
    - endpoints
    - ingresses
    - ingresses.extensions
    - namespaces
    - nodes
    - pods
    - pods/log
    - rolebindings
    - roles
    - secrets
    - serviceaccounts
    - services
    - statefulsets

  verbs:
    - get
    - list
    - watch
{{- end }}
